basePath: /
definitions:
  dto.Link:
    properties:
      text:
        example: Facebook da Ong
        type: string
      url:
        example: https://www.facebook.com/
        type: string
    type: object
  dto.OngUpdateDto:
    properties:
      adoptionPolicy:
        example: não pode rato
        type: string
      links:
        items:
          $ref: '#/definitions/dto.Link'
        type: array
      openingHours:
        example: "08:00"
        type: string
      phone:
        example: "119596995887"
        type: string
      user:
        $ref: '#/definitions/dto.UserUpdateDto'
    type: object
  dto.PetInsertDto:
    properties:
      adoption_date:
        example: "2008-01-02T15:04:05Z"
        type: string
      birthdate:
        example: "2006-01-02T15:04:05Z"
        type: string
      breed_id:
        example: 0e0b8399-1bf1-4ed5-a2f4-b5789ddf5df0
        type: string
      name:
        example: Thor
        type: string
      size:
        example: medium
        type: string
      user_id:
        example: fa1b8ae8-5351-11ef-8f02-0242ac130003
        type: string
      weight:
        example: 4.1
        type: number
    type: object
  dto.UserUpdateDto:
    properties:
      avatar_url:
        type: string
      birthdate:
        type: string
      document:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      pushNotificationsEnabled:
        type: boolean
      role:
        type: string
    type: object
host: localhost:3000/api
info:
  contact:
    name: DevHatt
    url: https://github.com/devhatt
  description: Esta página se destina a documentação da API do projeto PetDex Backend
  license:
    name: MIT license
    url: https://github.com/devhatt/pet-dex-backend?tab=MIT-1-ov-file#readme
  title: 'PetDex: Documentação API'
  version: "1.0"
paths:
  /ongs/{ongID}:
    patch:
      consumes:
      - application/json
      description: Retrieves Ong details based on the ong ID provided as a parameter.
      parameters:
      - description: Ong id to be retrieved
        in: path
        name: ongID
        required: true
        type: string
      - description: Update information of the ong
        in: body
        name: ongDto
        required: true
        schema:
          $ref: '#/definitions/dto.OngUpdateDto'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update Ong By ID
      tags:
      - Ong
  /pets/:
    post:
      consumes:
      - application/json
      description: Sends the Pet's registration data via the request body for persistence
        in the database.
      parameters:
      - description: Pet object information for registration
        in: body
        name: petDto
        required: true
        schema:
          $ref: '#/definitions/dto.PetInsertDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create Pet by petDto
      tags:
      - Pet
swagger: "2.0"
